name: simple_overlay_kit
description: "A unified Flutter overlay controller for OverlayEntry, OverlayRoute, and transition routes with configurable barriers."
version: 1.0.0
homepage: https://github.com/SimonWang9610/simple_overlay.git
repository: https://github.com/SimonWang9610/simple_overlay
issue_tracker: https://github.com/SimonWang9610/simple_overlay/issues

topics:
  - flutter
  - overlay
  - dialog
  - navigator
  - route

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
